Note that first the Fortran source file must be compiled with a Fortran compiler, for example ifort:

   ifort get_pdb_prop_CO.f90 -o get_pdb_prop_CO.exe

Then the following  Bash commands can be used to calculate Contact Orders:

   for file in ../../structures/* ; do get_pdb_prop_CO.exe $file ../pdb_prop_CO.out ; echo $file; done >& get_pdb_prop_CO.stdout &

for ASAP pdbs:

   for file in ../../structures_asap/* ; do get_pdb_prop_CO.exe $file ../pdb_prop_CO_asap.out ; echo $file; done >& get_pdb_prop_CO_asap.stdout &
