
# POWER-LAW WCN

    pdf( "../figures/mean_sp_wcnp_bfac.pdf", width=4.5, height=4, useDingbats=FALSE )
    plot(wcnp_bfac$parameter,wcnp_bfac$mean_sp, type = 'l', ylim=c(0.,0.8), xlab='power-law exponent', ylab='absolute spearman correlation: WCN-Bfactor', main='Power-law WCN')
    polygon(c(wcnp_bfac$parameter,rev(wcnp_bfac$parameter)),c(wcnp_bfac$quantile25_sp,rev(wcnp_bfac$quantile75_sp)),col = "green", border = FALSE)
    lspl = smooth.spline(wcnp_bfac$parameter,wcnp_bfac$quantile25_sp)
    uspl = smooth.spline(wcnp_bfac$parameter,wcnp_bfac$quantile75_sp)
    lines(wcnp_bfac$parameter,wcnp_bfac$mean_sp,lwd=2)
    lines(wcnp_bfac$parameter,wcnp_bfac$median_sp,lwd=2,lty=2)
    lines(predict(lspl,wcnp_bfac$parameter),lty=2,lwd=2,col='red')
    lines(predict(uspl,wcnp_bfac$parameter),lty=2,lwd=2,col='red')
    dev.off()

    pdf( "../figures/mean_sp_wcnp_seqent.pdf", width=4.5, height=4, useDingbats=FALSE )
    plot(wcnp_seqent$parameter,wcnp_seqent$mean_sp, type = 'l', ylim=c(0.,0.8), xlab='power-law exponent', ylab='absolute spearman correlation: WCN-SeqEnt', main='Power-law WCN')
    polygon(c(wcnp_seqent$parameter,rev(wcnp_seqent$parameter)),c(wcnp_seqent$quantile25_sp,rev(wcnp_seqent$quantile75_sp)),col = "green", border = FALSE)
    lspl = smooth.spline(wcnp_seqent$parameter,wcnp_seqent$quantile25_sp)
    uspl = smooth.spline(wcnp_seqent$parameter,wcnp_seqent$quantile75_sp)
    lines(wcnp_seqent$parameter,wcnp_seqent$mean_sp,lwd=2)
    lines(wcnp_seqent$parameter,wcnp_seqent$median_sp,lwd=2,lty=2)
    lines(predict(lspl,wcnp_seqent$parameter),lty=2,lwd=2,col='red')
    lines(predict(uspl,wcnp_seqent$parameter),lty=2,lwd=2,col='red')
    dev.off()

    
# GAUSSIAN WCN

    pdf( "../figures/mean_sp_wcng_bfac.pdf", width=4.5, height=4, useDingbats=FALSE )
    plot(wcng_bfac$parameter,wcng_bfac$mean_sp, type = 'l', ylim=c(0.,0.8), xlab='characteristic distance', ylab='spearman correlation: WCN-Bfactor', main='Gaussian WCN')
    polygon(c(wcng_bfac$parameter,rev(wcng_bfac$parameter)),c(wcng_bfac$quantile25_sp,rev(wcng_bfac$quantile75_sp)),col = "green", border = FALSE)
    lspl = smooth.spline(wcng_bfac$parameter,wcng_bfac$quantile25_sp)
    uspl = smooth.spline(wcng_bfac$parameter,wcng_bfac$quantile75_sp)
    lines(wcng_bfac$parameter,wcng_bfac$mean_sp,lwd=2)
    lines(wcng_bfac$parameter,wcng_bfac$median_sp,lwd=2,lty=2)
    lines(predict(lspl,wcng_bfac$parameter),lty=2,lwd=2,col='red')
    lines(predict(uspl,wcng_bfac$parameter),lty=2,lwd=2,col='red')
    dev.off()
    
    pdf( "../figures/mean_sp_wcng_seqent.pdf", width=4.5, height=4, useDingbats=FALSE )
    plot(wcng_seqent$parameter,wcng_seqent$mean_sp, type = 'l', ylim=c(0.,0.8), xlab='characteristic distance', ylab='spearman correlation: WCN-SeqEnt', main='Gaussian WCN')
    polygon(c(wcng_seqent$parameter,rev(wcng_seqent$parameter)),c(wcng_seqent$quantile25_sp,rev(wcng_seqent$quantile75_sp)),col = "green", border = FALSE)
    lspl = smooth.spline(wcng_seqent$parameter,wcng_seqent$quantile25_sp)
    uspl = smooth.spline(wcng_seqent$parameter,wcng_seqent$quantile75_sp)
    lines(wcng_seqent$parameter,wcng_seqent$mean_sp,lwd=2)
    lines(wcng_seqent$parameter,wcng_seqent$median_sp,lwd=2,lty=2)
    lines(predict(lspl,wcng_seqent$parameter),lty=2,lwd=2,col='red')
    lines(predict(uspl,wcng_seqent$parameter),lty=2,lwd=2,col='red')
    dev.off()
    
# EXPONENTIAL WCN

    pdf( "../figures/mean_sp_wcne_bfac.pdf", width=4.5, height=4, useDingbats=FALSE )
    plot(wcne_bfac$parameter,wcne_bfac$mean_sp, type = 'l', ylim=c(0.,0.8), xlab='characteristic distance', ylab='spearman correlation: WCN-Bfactor', main='Exponential WCN')
    polygon(c(wcne_bfac$parameter,rev(wcne_bfac$parameter)),c(wcne_bfac$quantile25_sp,rev(wcne_bfac$quantile75_sp)),col = "green", border = FALSE)
    lspl = smooth.spline(wcne_bfac$parameter,wcne_bfac$quantile25_sp)
    uspl = smooth.spline(wcne_bfac$parameter,wcne_bfac$quantile75_sp)
    lines(wcne_bfac$parameter,wcne_bfac$mean_sp,lwd=2)
    lines(wcne_bfac$parameter,wcne_bfac$median_sp,lwd=2,lty=2)
    lines(predict(lspl,wcne_bfac$parameter),lty=2,lwd=2,col='red')
    lines(predict(uspl,wcne_bfac$parameter),lty=2,lwd=2,col='red')
    dev.off()

    pdf( "../figures/mean_sp_wcne_seqent.pdf", width=4.5, height=4, useDingbats=FALSE )
    plot(wcne_seqent$parameter,wcne_seqent$mean_sp, type = 'l', ylim=c(0.,0.8), xlab='characteristic distance', ylab='spearman correlation: WCN-SeqEnt', main='Exponential WCN')
    polygon(c(wcne_seqent$parameter,rev(wcne_seqent$parameter)),c(wcne_seqent$quantile25_sp,rev(wcne_seqent$quantile75_sp)),col = "green", border = FALSE)
    lspl = smooth.spline(wcne_seqent$parameter,wcne_seqent$quantile25_sp)
    uspl = smooth.spline(wcne_seqent$parameter,wcne_seqent$quantile75_sp)
    lines(wcne_seqent$parameter,wcne_seqent$mean_sp,lwd=2)
    lines(wcne_seqent$parameter,wcne_seqent$median_sp,lwd=2,lty=2)
    lines(predict(lspl,wcne_seqent$parameter),lty=2,lwd=2,col='red')
    lines(predict(uspl,wcne_seqent$parameter),lty=2,lwd=2,col='red')
    dev.off()
    
# DENSITY WCN

    pdf( "../figures/mean_sp_wcnd_bfac.pdf", width=4.5, height=4, useDingbats=FALSE )
    plot(wcnd_bfac$parameter,wcnd_bfac$mean_sp, type = 'l', ylim=c(0.,0.8), xlab='cutoff distance [Angstroms]', ylab='correlation: WCN-Bfactor', main='Density CN')
    polygon(c(wcnd_bfac$parameter,rev(wcnd_bfac$parameter)),c(wcnd_bfac$quantile25_sp,rev(wcnd_bfac$quantile75_sp)),col = "green", border = FALSE)
    lspl = smooth.spline(wcnd_bfac$parameter,wcnd_bfac$quantile25_sp)
    uspl = smooth.spline(wcnd_bfac$parameter,wcnd_bfac$quantile75_sp)
    lines(wcnd_bfac$parameter,wcnd_bfac$mean_sp,lwd=2)
    lines(wcnd_bfac$parameter,wcnd_bfac$median_sp,lwd=2,lty=2)
    lines(predict(lspl,wcnd_bfac$parameter),lty=2,lwd=2,col='red')
    lines(predict(uspl,wcnd_bfac$parameter),lty=2,lwd=2,col='red')
    dev.off()

    pdf( "../figures/mean_sp_wcnd_seqent.pdf", width=4.5, height=4, useDingbats=FALSE )
    plot(wcnd_seqent$parameter,wcnd_seqent$mean_sp, type = 'l', ylim=c(0.,0.6), xlab='cutoff distance [Angstroms]', ylab='Spearman correlation strength') #, main='Density CN')
    polygon(c(wcnd_seqent$parameter,rev(wcnd_seqent$parameter)),c(wcnd_seqent$quantile25_sp,rev(wcnd_seqent$quantile75_sp)),col = "green", border = FALSE)
    lspl = smooth.spline(wcnd_seqent$parameter,wcnd_seqent$quantile25_sp)
    uspl = smooth.spline(wcnd_seqent$parameter,wcnd_seqent$quantile75_sp)
    lines(wcnd_seqent$parameter,wcnd_seqent$mean_sp,lwd=2)
    lines(wcnd_seqent$parameter,wcnd_seqent$median_sp,lwd=2,lty=2)
    lines(predict(lspl,wcnd_seqent$parameter),lty=2,lwd=2,col='red')
    lines(predict(uspl,wcnd_seqent$parameter),lty=2,lwd=2,col='red')
    dev.off()
